INSERT INTO proxy_login (
    from_user_id,
    from_name,
    from_email,
    from_picture_url,
    from_box_user_id,
    from_box_access_token,
    from_box_refresh_token,
    from_role_id,
    to_user_id,
    to_name,
    to_email,
    to_picture_url,
    to_box_user_id,
    to_box_access_token,
    to_box_refresh_token,
    to_role_id
)
VALUES (
    :from_user_id,
    :from_name,
    :from_email,
    :from_picture_url,
    :from_box_user_id,
    :from_box_access_token,
    :from_box_refresh_token,
    :from_role_id,
    :to_user_id,
    :to_name,
    :to_email,
    :to_picture_url,
    :to_box_user_id,
    :to_box_access_token,
    :to_box_refresh_token,
    :to_role_id
)
ON DUPLICATE KEY UPDATE
    from_name = VALUES(from_name),
    from_email = VALUES(from_email),
    from_picture_url = VALUES(from_picture_url),
    from_box_user_id = VALUES(from_box_user_id),
    from_box_access_token = VALUES(from_box_access_token),
    from_box_refresh_token = VALUES(from_box_refresh_token),
    from_role_id = VALUES(from_role_id),
    to_name = VALUES(to_name),
    to_email = VALUES(to_email),
    to_picture_url = VALUES(to_picture_url),
    to_box_user_id = VALUES(to_box_user_id),
    to_box_access_token = VALUES(to_box_access_token),
    to_box_refresh_token = VALUES(to_box_refresh_token),
    to_role_id = VALUES(to_role_id),
    updated_at = CURRENT_TIMESTAMP;