DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
    id CHAR(255) NOT NULL PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(512),
    level int,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);